### PR TITLE
Fix exception when loading certain GIFs

### PR DESCRIPTION
**Pull request by ChlorideCull**
WebM and MP4 isn't always available, so first check if they are.

### CODE REVIEW

**Comment by luckydonald** [comment]
Shouldn't they default to null otherwise?

**Comment by ChlorideCull** [comment]
In the API of Derpibooru or DerPyBooru? It seems they might have even been removed completely, I can't find any posts which contain them.

**Comment by luckydonald** [comment]
If the tag isn't present on derpibooru, it should still be in DerPyBooru.
So you can just check if it is None.
(if they do still exist... that is)

**Comment by ChlorideCull** [comment]
Well, they don't exist on the derpibooru API it seems, even on [uploads tagged as 'webm'](https://derpibooru.org/957341.json), and it seems it was never even supported, so I don't actually know where it came from.

**Comment by liamwhite** [comment]
@ChlorideCull Currently you need to have WebM serving enabled in your API user's settings. (Display->Serve webm)

**Comment by luckydonald** [comment]
that should be enable-ble with a param on searches, lists, images
Actually I don't see a reason why to disable it on the api, if all available types are included, the client still can choose.

**Comment by LoganDark** [comment]
Seems to be the case with #15.

**Comment by joshua-stone** [comment]
I've removed support for webm/mp4 representations for GIFs as the API no longer exposes them. They were never a documented feature, so adding them to the library was never a good idea.

**Comment by luckydonald** [comment]
0bc66e695d83074dec3597e16605764d9abad5c3

**Comment by LoganDark** [comment]
yes I can see

**Pull request closed without merging**
