### PR TITLE
Implemented Filters

### PR DESCRIPTION
**Pull request by luckydonald**
Implement the filter keyword for Issue **Use Filter #8**

### CODE REVIEW

**Comment by Nuke928** [comment]
Maintainer seems to be dead. What do?

**Comment by luckydonald** [comment]
ping @joshua-stone (so he maybe gets an email)

I wonder how Internet looks like in the next few generation, when all we are dead.
So many facebook profiles with age 149+.
I mean, you cant say in your testament "delete all my accounts!"
I am getting of topic here.

Maybe fork it?
I'd do it, but have no time until after the next week.

**Comment by liamwhite** [comment]
JFYI, maintainer is not dead.

**Comment by luckydonald** [comment]
Great!

**Pull request merged**
